import {useEffect,useMemo,useState} from 'react';
import {auth,students,complaints,events,notices} from './services/api';
import type {AuthResponse,Student,Complaint,Event,Notice,Role} from './types';

type Tab='overview'|'complaints'|'events'|'notices'|'profile'|'students';
const saveSession=(a:AuthResponse)=>{localStorage.setItem('campus_token',a.token);localStorage.setItem('campus_role',a.role);localStorage.setItem('campus_email',a.email)};
const role=()=>localStorage.getItem('campus_role') as Role|null;

function Auth({onLogin}:{onLogin:()=>void}){const [mode,setMode]=useState<'login'|'register'>('login');const [form,setForm]=useState<any>({});const [error,setError]=useState('');const set=(k:string,v:string)=>setForm((x:any)=>({...x,[k]:v}));
 const submit=async(e:any)=>{e.preventDefault();setError('');try{const r=mode==='login'?await auth.login({email:form.email,password:form.password}):await auth.register(form);saveSession(r.data);onLogin()}catch(err:any){setError(err.response?.data?.message||'Unable to complete request')}};
 return <main className="auth"><div className="auth-card"><div className="brand">CS<span>MS</span></div><h1>{mode==='login'?'Welcome back':'Create student account'}</h1><p>{mode==='login'?'Sign in to access campus services.':'Register to submit and track campus requests.'}</p><form onSubmit={submit}>
 <input required type="email" placeholder="Email" onChange={e=>set('email',e.target.value)}/><input required type="password" placeholder="Password" minLength={6} onChange={e=>set('password',e.target.value)}/>
 {mode==='register'&&<><input required placeholder="Full name" onChange={e=>set('fullName',e.target.value)}/><input required placeholder="Roll number" onChange={e=>set('rollNumber',e.target.value)}/><input placeholder="Department" onChange={e=>set('department',e.target.value)}/><input placeholder="Year" onChange={e=>set('year',e.target.value)}/><input placeholder="Phone" onChange={e=>set('phone',e.target.value)}/></>}
 {error&&<div className="error">{error}</div>}<button className="primary">{mode==='login'?'Sign in':'Register'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New student? Create account':'Already registered? Sign in'}</button></div></main>}

function Layout({tab,setTab,onLogout,children}:{tab:Tab;setTab:(t:Tab)=>void;onLogout:()=>void;children:any}){const r=role();const nav:Tab[]=['overview','complaints','events','notices','profile',...(r==='ADMIN'?['students' as Tab]:[])];return <div className="layout"><aside><div className="brand">CS<span>MS</span></div><small>{r} PORTAL</small>{nav.map(n=><button key={n} className={tab===n?'nav active':'nav'} onClick={()=>setTab(n)}>{n[0].toUpperCase()+n.slice(1)}</button>)}<button className="nav logout" onClick={onLogout}>Sign out</button></aside><section className="content"><header><div><small>Campus Services</small><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2></div><div className="user-pill">{localStorage.getItem('campus_email')}</div></header>{children}</section></div>}

function Overview({setTab}:{setTab:(t:Tab)=>void}){const [data,setData]=useState({c:0,e:0,n:0});useEffect(()=>{Promise.all([complaints.mine().catch(()=>({data:[]})),events.list(),notices.list()]).then(([c,e,n])=>setData({c:c.data.length,e:e.data.length,n:n.data.length}))},[]);return <><div className="hero-panel"><span className="eyebrow">Campus command center</span><h1>Everything your campus needs, in one place.</h1><p>Manage complaints, discover events, read notices and keep your student profile current.</p></div><div className="stats"><button onClick={()=>setTab('complaints')}><b>{data.c}</b><span>My complaints</span></button><button onClick={()=>setTab('events')}><b>{data.e}</b><span>Upcoming events</span></button><button onClick={()=>setTab('notices')}><b>{data.n}</b><span>Active notices</span></button></div></>}

function Complaints(){const r=role();const [items,setItems]=useState<Complaint[]>([]);const [q,setQ]=useState('');const [form,setForm]=useState({title:'',description:'',category:''});const load=()=>{(r==='ADMIN'?complaints.all():complaints.mine()).then(x=>setItems(x.data))};useEffect(load,[]);const filtered=useMemo(()=>items.filter(x=>(x.title+' '+x.description+' '+(x.category||'')).toLowerCase().includes(q.toLowerCase())),[items,q]);const create=async(e:any)=>{e.preventDefault();await complaints.create(form);setForm({title:'',description:'',category:''});load()};const status=async(id:number,s:string)=>{await complaints.status(id,s);load()};return <><div className="toolbar"><input placeholder="Search complaints..." value={q} onChange={e=>setQ(e.target.value)}/>{r==='STUDENT'&&<span className="muted">Submit a ticket below</span>}</div>{r==='STUDENT'&&<form className="panel form-grid" onSubmit={create}><input required placeholder="Complaint title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><textarea required placeholder="Describe the issue" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary">Submit complaint</button></form>}<div className="list">{filtered.map(c=><article className="panel item" key={c.id}><div><span className={'badge '+c.status}>{c.status.replace('_',' ')}</span><h3>{c.title}</h3><p>{c.description}</p><small>{c.category||'General'} · {new Date(c.createdAt).toLocaleString()}</small></div>{r==='ADMIN'&&<select value={c.status} onChange={e=>status(c.id,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select>}</article>)}{!filtered.length&&<div className="empty">No complaints found.</div>}</div></>}

function Events(){const r=role();const [items,setItems]=useState<Event[]>([]);const [form,setForm]=useState<Event>({title:'',description:'',eventDate:'',venue:'',organizer:''});const load=()=>events.list().then(x=>setItems(x.data));useEffect(load,[]);const submit=async(e:any)=>{e.preventDefault();await events.create(form);setForm({title:'',description:'',eventDate:'',venue:'',organizer:''});load()};return <><div className="section-title"><p>Upcoming campus events</p></div>{r==='ADMIN'&&<form className="panel form-grid" onSubmit={submit}><input required placeholder="Event title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required type="datetime-local" value={form.eventDate} onChange={e=>setForm({...form,eventDate:e.target.value})}/><input placeholder="Venue" value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/><input placeholder="Organizer" value={form.organizer} onChange={e=>setForm({...form,organizer:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary">Create event</button></form>}<div className="cards">{items.map(e=><article className="panel card" key={e.id}><span className="date">{new Date(e.eventDate).toLocaleDateString()}</span><h3>{e.title}</h3><p>{e.description}</p><small>{e.venue||'Venue TBA'} · {e.organizer||'Campus'}</small>{r==='ADMIN'&&<button className="danger" onClick={async()=>{await events.remove(e.id!);load()}}>Delete</button>}</article>)}</div></>}

function Notices(){const r=role();const [items,setItems]=useState<Notice[]>([]);const [form,setForm]=useState<Notice>({title:'',content:'',category:''});const load=()=>notices.list().then(x=>setItems(x.data));useEffect(load,[]);const submit=async(e:any)=>{e.preventDefault();await notices.create(form);setForm({title:'',content:'',category:''});load()};return <><p>Official campus announcements and updates.</p>{r==='ADMIN'&&<form className="panel form-grid" onSubmit={submit}><input required placeholder="Notice title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><textarea required placeholder="Notice content" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/><button className="primary">Publish notice</button></form>}<div className="list">{items.map(n=><article className="panel item" key={n.id}><div><span className="badge OPEN">{n.category||'NOTICE'}</span><h3>{n.title}</h3><p>{n.content}</p><small>{n.publishedAt&&new Date(n.publishedAt).toLocaleString()}</small></div>{r==='ADMIN'&&<button className="danger" onClick={async()=>{await notices.remove(n.id!);load()}}>Delete</button>}</article>)}</div></>}

function Profile(){const [s,setS]=useState<Student|null>(null);const [editing,setEditing]=useState(false);useEffect(()=>{students.profile().then(x=>setS(x.data))},[]);if(!s)return <div className="empty">Loading profile...</div>;return <div className="panel profile"><div className="avatar">{s.fullName[0]}</div><h2>{s.fullName}</h2><p>{s.rollNumber} · {s.department||'Department not set'}</p>{editing?<ProfileForm s={s} onSave={x=>{setS(x);setEditing(false)}}/>:<><dl><dt>Email</dt><dd>{s.user?.email||localStorage.getItem('campus_email')}</dd><dt>Year</dt><dd>{s.year||'—'}</dd><dt>Phone</dt><dd>{s.phone||'—'}</dd></dl><button className="primary" onClick={()=>setEditing(true)}>Edit profile</button></>}</div>}
function ProfileForm({s,onSave}:{s:Student;onSave:(s:Student)=>void}){const [f,setF]=useState(s);return <form className="form-grid" onSubmit={async e=>{e.preventDefault();const r=await students.update(f);onSave(r.data)}}><input value={f.fullName} onChange={e=>setF({...f,fullName:e.target.value})}/><input value={f.department||''} onChange={e=>setF({...f,department:e.target.value})}/><input value={f.year||''} onChange={e=>setF({...f,year:e.target.value})}/><input value={f.phone||''} onChange={e=>setF({...f,phone:e.target.value})}/><button className="primary">Save changes</button></form>}
function Students(){const [items,setItems]=useState<Student[]>([]);const [q,setQ]=useState('');useEffect(()=>{students.all().then(x=>setItems(x.data))},[]);const f=items.filter(s=>(s.fullName+' '+s.rollNumber+' '+(s.department||'')).toLowerCase().includes(q.toLowerCase()));return <><div className="toolbar"><input placeholder="Search students..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="panel table"><div className="tr head"><b>Name</b><b>Roll No.</b><b>Department</b><b>Year</b></div>{f.map(s=><div className="tr" key={s.id}><span>{s.fullName}</span><span>{s.rollNumber}</span><span>{s.department||'—'}</span><span>{s.year||'—'}</span></div>)}</div></>}

function App(){const [logged,setLogged]=useState(!!localStorage.getItem('campus_token'));const [tab,setTab]=useState<Tab>('overview');const logout=()=>{localStorage.clear();setLogged(false)};if(!logged)return <Auth onLogin={()=>setLogged(true)}/>;return <Layout tab={tab} setTab={setTab} onLogout={logout}>{tab==='overview'&&<Overview setTab={setTab}/>} {tab==='complaints'&&<Complaints/>}{tab==='events'&&<Events/>}{tab==='notices'&&<Notices/>}{tab==='profile'&&<Profile/>}{tab==='students'&&<Students/>}</Layout>}
export default App;
