const serviceOptions = ['Custodian Certificate','Bonafide','Transfer Certificate','Bonafide And Conduct Certificate'];
const style = document.createElement('style');
style.textContent = `.csms-services-page{padding:0 0 32px}.csms-services-box{background:#fff;border:1px solid #e1e6ef;border-radius:18px;padding:28px}.csms-services-box h1{margin:7px 0 8px;font-size:30px}.csms-services-box p{color:#6b778c;line-height:1.6;margin:0 0 24px}.csms-services-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.csms-service{border:1px solid #e1e6ef;background:#fff;border-radius:14px;padding:22px;text-align:left;cursor:pointer}.csms-service:hover{border-color:#bfc9df;transform:translateY(-1px);box-shadow:0 8px 24px #1720330d}.csms-service b{display:block;font-size:13px}.csms-service span{display:block;color:#778297;font-size:11px;margin-top:7px}.csms-modal{position:fixed;inset:0;z-index:10000;background:#0f172a99;display:grid;place-items:center;padding:20px}.csms-modal-card{width:min(680px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:26px}.csms-modal-head{display:flex;justify-content:space-between}.csms-close{border:0;background:none;font-size:27px;cursor:pointer}.csms-form{display:grid;gap:13px;margin-top:18px}.csms-form label{display:grid;gap:6px;font-size:12px;font-weight:700}.csms-form input,.csms-form textarea{padding:12px;border:1px solid #dbe1eb;border-radius:10px}.csms-form textarea{min-height:90px}.csms-actions{display:flex;justify-content:flex-end;gap:8px}.csms-msg{font-size:12px;color:#147447}.csms-nav{display:flex!important;align-items:center;gap:14px;width:100%;text-align:left;cursor:pointer}.csms-nav.active{background:#20283a!important;color:#fff!important}@media(max-width:1000px){.csms-services-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.csms-services-grid{grid-template-columns:1fr}}`;
document.head.appendChild(style);

const openService = (service:string) => { document.querySelector('.csms-modal')?.remove(); const overlay=document.createElement('div'); overlay.className='csms-modal'; overlay.innerHTML=`<div class="csms-modal-card"><div class="csms-modal-head"><div><span class="eyebrow">Student Services</span><h2 style="margin:7px 0">${service}</h2><p style="color:#6b778c">Submit a request for this service.</p></div><button class="csms-close">×</button></div><form class="csms-form"><label>Full name<input required name="name" placeholder="Your full name"></label><label>Roll number<input required name="rollNumber" placeholder="Your roll number"></label><label>Gmail<input required type="email" name="email" pattern="[A-Za-z0-9._%+-]+@gmail\\.com" placeholder="you@gmail.com"></label><label>Phone number<input required name="phone" inputmode="tel" placeholder="9876543210"></label><label>Additional details<textarea name="details" placeholder="Add any required information..."></textarea></label><div class="csms-msg"></div><div class="csms-actions"><button type="button" class="secondary csms-cancel">Cancel</button><button class="primary">Submit Request</button></div></form></div>`; document.body.appendChild(overlay); const close=()=>overlay.remove(); overlay.querySelector('.csms-close')?.addEventListener('click',close); overlay.querySelector('.csms-cancel')?.addEventListener('click',close); overlay.addEventListener('click',e=>{if(e.target===overlay)close()}); overlay.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();(overlay.querySelector('.csms-msg') as HTMLElement).textContent='Request submitted successfully.'}); };

const addStudentServicesNav=()=>{const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-student-services-nav]'))return;const eventButton=Array.from(nav.querySelectorAll<HTMLButtonElement>('.nav')).find(b=>b.textContent?.trim().toLowerCase()==='events');if(!eventButton)return;const button=document.createElement('button');button.className='nav csms-nav';button.dataset.studentServicesNav='true';button.innerHTML='<span class="nav-icon">▣</span>Student Services';button.addEventListener('click',()=>showStudentServices(button));eventButton.insertAdjacentElement('afterend',button)};

const showStudentServices=(button:HTMLButtonElement)=>{const content=document.querySelector('.content');const header=content?.querySelector('header');if(!content||!header)return;document.querySelector('.csms-services-page')?.remove();Array.from(content.children).forEach((el,i)=>{if(i>0)(el as HTMLElement).style.display='none'});const title=header.querySelector('h2');if(title)title.textContent='Student Services';const page=document.createElement('section');page.className='csms-services-page';page.innerHTML=`<div class="csms-services-box"><span class="eyebrow">Student Services</span><h1>Student Services</h1><p>Request common academic and student documents directly from the campus portal.</p><div class="csms-services-grid">${serviceOptions.map(s=>`<button class="csms-service" data-service="${s}"><b>${s}</b><span>Click to create a service request</span></button>`).join('')}</div></div>`;header.insertAdjacentElement('afterend',page);document.querySelectorAll('.csms-nav').forEach(x=>x.classList.remove('active'));button.classList.add('active');page.querySelectorAll<HTMLButtonElement>('[data-service]').forEach(b=>b.addEventListener('click',()=>openService(b.dataset.service||'Student Service')))};

const exit=()=>{document.querySelector('.csms-services-page')?.remove();document.querySelector('.csms-modal')?.remove();const content=document.querySelector('.content');if(content)Array.from(content.children).forEach((el,i)=>{if(i>0)(el as HTMLElement).style.display=''});document.querySelectorAll('.csms-nav').forEach(x=>x.classList.remove('active'))};
const observer=new MutationObserver(()=>{addStudentServicesNav();if(!document.querySelector('.csms-services-page')){const nav=document.querySelector('aside nav');nav?.querySelectorAll<HTMLButtonElement>('.nav:not(.csms-nav)').forEach(b=>{if(b.dataset.csmsExit==='true')return;b.dataset.csmsExit='true';b.addEventListener('click',exit)})}});observer.observe(document.body,{childList:true,subtree:true});setTimeout(addStudentServicesNav,200);